// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "HelloService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include <iostream>
#include <string>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::demo;

/*编译命令：
 * g++ HelloService.cpp hello_types.cpp cpp_server.cpp -g -I /home/mi/Project/Thrift/installed/include/ -L /home/mi/Project/Thrift/installed/lib/ -lthrift -pthread -o cpp-server
 * */

class HelloServiceHandler : virtual public HelloServiceIf {
 public:
  HelloServiceHandler() {
    // Your initialization goes here
  }

  void helloFunc(std::string& _return, const std::string& para) {
    // Your implementation goes here
      std::cout << para << std::endl;
      _return = "(Returned from Cpp Server) Original message: " + para;
  }

};

int main(int argc, char **argv) {
  int port = 2345;
  shared_ptr<HelloServiceHandler> handler(new HelloServiceHandler());
  shared_ptr<TProcessor> processor(new HelloServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

