/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "hello_constants.h"

namespace demo {

const helloConstants g_hello_constants;

helloConstants::helloConstants() {
}

} // namespace

